apiVersion: v1
kind: Service
metadata:
  name: blogpost-service
spec:
  selector:
    app: blogpost
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 of the service
      targetPort: 3000  # Forward traffic to port 3000 on the pods
  type: LoadBalancer  # Used LoadBalancer type to expose externally 
